---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demo1
 labels:
  app: demo1
spec:
 replicas: 1
 selector:
  matchLabels:
   app: demo1
 template:
  metadata: 
   labels:
    app: demo1
  spec:
   containers:
   - name: demo1
     image: gcr.io/jenkins-407204/demo:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  type: LoadBalancer
  selector:
    app: demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
