---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-deployment-loadbalancer
 labels:
  app: myapp-app-loadbalancer
spec:
 replicas: 1
 selector:
  matchLabels:
   app: demo1-loadbalancer
 template:
  metadata: 
   labels:
    app: demo1-loadbalancer
  spec:
   containers:
   - name: demo1-loadbalancer
     image: gcr.io/jenkins-407204/demo:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: demo1-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: demo1-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
